import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import { ProductResponse } from '../../src/typings';

export default function ProductPage() {
  const { query } = useRouter();
  const { code } = query;

  const [productResponse, setProductResponse] = useState<ProductResponse>();

  useEffect(() => {
    if (code && code?.length > 0) {
      fetch(`https://world.openfoodfacts.org/api/v0/product/${code}.json`)
        .then(response => response.json() as Promise<ProductResponse>)
        .then(data => {
          setProductResponse(data);
        });
    }
  }, [code]);

  return (
    <>
      <Head>
        <title>OFF Scanner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{code}</div>
      {productResponse?.status ? (
        <div>
          <p>{productResponse.product.product_name}</p>
          <p>{productResponse.product.generic_name}</p>
          <p>{productResponse.product.quantity}</p>
          <p>{productResponse.product.brands}</p>
          <p>{productResponse.product.ingredients_text}</p>
        </div>
      ) : (
        <p>No product found</p>
      )}
    </>
  );
}
